const list = [
  {
    id: 0,
    title: "Diabetics",
    description:
      "Diabetes is a chronic (long-lasting) health condition that affects how your body turns food into energy. Your body breaks down most of the food you eat into sugar (glucose) and releases it into your bloodstream. When your blood sugar goes up, it signals your pancreas to release insulin.",
    author: "Arnab Bhattacharya",
    commentCount: 3,
    category: [""],
    upvote: 10,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "173k",
    shares: "1.2k",
  },
  {
    id: 1,
    title: "Cancer",
    description: "Cancer is a group of diseases characterized by the uncontrolled growth and spread of abnormal cells. If left untreated, cancer can cause serious illness and death.",
    author: "Samantha Smith",
    commentCount: 5,
    upvote: 15,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "89k",
    shares: "11k",
  },
  {
    id: 2,
    title: "Heart Disease",
    description: "Heart disease is a broad term that refers to any type of disorder that affects the heart. It is a leading cause of death worldwide.",
    author: "John Doe",
    commentCount: 2,
    upvote: 8,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "45k",
    shares: "7.1k",
  },
  {
    id: 3,
    title: "Stroke",
    description:
      "A stroke is a serious, life-threatening medical condition that occurs when the blood supply to part of the brain is cut off. Symptoms of a stroke include weakness, numbness, and difficulty speaking or understanding speech.",
    author: "Jane Doe",
    commentCount: 4,
    upvote: 12,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "100k",
    shares: "5k",
  },
  {
    id: 4,
    title: "Asthma",
    description: "Asthma is a chronic respiratory disease characterized by inflammation of the airways and difficulty breathing. Symptoms include coughing, wheezing, and shortness of breath.",
    author: "Mike Smith",
    commentCount: 3,
    upvote: 9,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "70k",
    shares: "3.1k",
  },
  {
    id: 5,
    title: "Influenza",
    description: "Influenza, also known as the flu, is a highly contagious respiratory illness caused by the influenza virus. Symptoms include fever, cough, sore throat, and body aches.",
    author: "Emma Watson",
    commentCount: 6,
    upvote: -7,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "120k",
    shares: "1.3k",
  },
  {
    id: 6,
    title: "Chronic Obstructive Pulmonary Disease (COPD)",
    description:
      "Chronic obstructive pulmonary disease (COPD) is a chronic inflammatory lung disease that causes obstructed airflow from the lungs. Symptoms include breathing difficulty, cough, mucus (sputum) production and wheezing",
    author: "Mike Smith",
    commentCount: 3,
    upvote: 9,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "70k",
    shares: "1.2k",
  },
  {
    id: 7,
    title: "Diabetics",
    description:
      "Diabetes is a chronic (long-lasting) health condition that affects how your body turns food into energy. Your body breaks down most of the food you eat into sugar (glucose) and releases it into your bloodstream. When your blood sugar goes up, it signals your pancreas to release insulin.",
    author: "Arnab Bhattacharya",
    commentCount: 3,
    upvote: 10,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "173k",
    shares: "1.2k",
  },
  {
    id: 8,
    title: "Cancer",
    description: "Cancer is a group of diseases characterized by the uncontrolled growth and spread of abnormal cells. If left untreated, cancer can cause serious illness and death.",
    author: "Samantha Smith",
    commentCount: 5,
    upvote: -15,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "89k",
    shares: "1.2k",
  },
  {
    id: 9,
    title: "Heart Disease",
    description: "Heart disease is a broad term that refers to any type of disorder that affects the heart. It is a leading cause of death worldwide.",
    author: "John Doe",
    commentCount: 2,
    upvote: 8,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "45k",
    shares: "1.2k",
  },
  {
    id: 10,
    title: "Stroke",
    description:
      "A stroke is a serious, life-threatening medical condition that occurs when the blood supply to part of the brain is cut off. Symptoms of a stroke include weakness, numbness, and difficulty speaking or understanding speech.",
    author: "Jane Doe",
    commentCount: 4,
    upvote: -12,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "100k",
    shares: "1.2k",
  },
  {
    id: 11,
    title: "Asthma",
    description: "Asthma is a chronic respiratory disease characterized by inflammation of the airways and difficulty breathing. Symptoms include coughing, wheezing, and shortness of breath.",
    author: "Mike Smith",
    commentCount: 3,
    upvote: 9,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "70k",
    shares: "1.2k",
  },
  {
    id: 12,
    title: "Influenza",
    description: "Influenza, also known as the flu, is a highly contagious respiratory illness caused by the influenza virus. Symptoms include fever, cough, sore throat, and body aches.",
    author: "Emma Watson",
    commentCount: 6,
    upvote: 17,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "120k",
    shares: "1.2k",
  },
  {
    id: 13,
    title: "Chronic Obstructive Pulmonary Disease (COPD)",
    description:
      "Chronic obstructive pulmonary disease (COPD) is a chronic inflammatory lung disease that causes obstructed airflow from the lungs. Symptoms include breathing difficulty, cough, mucus (sputum) production and wheezing",
    author: "Mike Smith",
    commentCount: 3,
    upvote: 9,
    createdAt: new Date().getTime(),
    updatedAt: new Date().getTime(),
    views: "70k",
    shares: "1.2k",
  },
];

export { list };
